modules/bash: modules/bash/**
modules/bumpversion: modules/bumpversion/**
modules/completion: modules/completion/**
modules/compose: modules/compose/**
modules/django: modules/django/**
modules/docker: modules/docker/**
modules/docs: modules/docs/**
modules/faas: modules/faas/**
modules/git: modules/git/**
modules/github: modules/github/**
modules/gitleaks: modules/gitleaks/**
modules/go: modules/go/**
modules/helm: modules/helm/**
modules/helmfile: modules/helmfile/**
modules/jenkins: modules/jenkins/**
modules/make: modules/make/**
modules/packages: modules/packages/**
modules/pipenv: modules/pipenv/**
modules/pytest: modules/pytest/**
modules/python: modules/python/**
modules/readme: modules/readme/**
modules/semver: modules/semver/**
modules/template: modules/template/**
modules/terraform: modules/terraform/**
modules/travis: modules/travis/**
